import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">

        <header className="sticky top-0 z-50 backdrop-blur-sm bg-white/10 border-b">
          <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
            <a href="/" className="font-extrabold tracking-tight text-lg md:text-xl text-sky-800">Tharani Sebi George</a>
            <nav className="flex gap-6 text-sm text-slate-700">
              <a href="/" className="hover:text-slate-900">Home</a>
              <a href="/about" className="hover:text-slate-900">About</a>
              <a href="/projects" className="hover:text-slate-900">Projects</a>
              <a href="/blog" className="hover:text-slate-900">Blog</a>
              <a href="/contact" className="hover:text-slate-900">Contact</a>
            </nav>
          </div>
        </header>

        <main className="flex-1">{children}</main>

      </body>
    </html>
  );
}
